# Generated by Django 4.1.7 on 2025-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('treatments', models.TextField(blank=True, null=True)),
                ('disease_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('contagious', models.BooleanField(default=False)),
                ('chronic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='diseases_di_name_f1e1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['disease_code'], name='diseases_di_disease_969400_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['contagious'], name='diseases_di_contagi_5e715e_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['chronic'], name='diseases_di_chronic_23400c_idx'),
        ),
    ]
